# Generated by Django 2.2.5 on 2019-09-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaildigest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'weekly'), ('daily', 'daily')], default='daily', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='weekly_weekday',
            field=models.CharField(blank=True, choices=[('Sun', 'Sun'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat')], max_length=16, null=True),
        ),
    ]
