# Generated by Django 2.2.5 on 2019-09-23 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emaildigest', '0002_auto_20190923_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoussubscription',
            name='logged_in_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='verfied_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
