# Generated by Django 2.2.5 on 2019-09-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
