# Generated by Django 2.2.5 on 2019-09-08 16:42

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_story_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='to_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.Story'),
        ),
        migrations.AlterField(
            model_name='item',
            name='downvotes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='num_comments',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='news.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='points',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='upvotes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
