# Generated by Django 2.2.5 on 2019-09-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190908_1642'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['points', 'created_at'], name='news_item_points_d03885_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at', 'points'], name='news_item_created_f2b812_idx'),
        ),
    ]
