# Generated by Django 2.2.5 on 2019-09-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190908_2251'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='news_item_points_d03885_idx',
        ),
        migrations.AddField(
            model_name='item',
            name='is_ask',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at', 'points'], name='news_item_created_f2b812_idx'),
        ),
    ]
