# Generated by Django 2.2.5 on 2019-09-23 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190908_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='duplicate_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Story'),
        ),
    ]
