# Generated by Django 2.2.5 on 2019-09-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_story_duplicate_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
