# Generated by Django 2.2.5 on 2019-09-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20190930_1620'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['domain', 'duplicate_of'], name='news_story_domain_07db78_idx'),
        ),
    ]
