# Generated by Django 2.2.5 on 2019-09-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20190930_1623'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['created_at', 'id'], name='news_item_created_10dd57_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['id', 'created_at'], name='news_item_id_b557ce_idx'),
        ),
    ]
