# Generated by Django 2.2.5 on 2019-09-15 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190915_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
